version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  task:
    build: ./task
    restart: always
    hostname: task
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  mailer:
    build: ./mailer
    restart: always
    hostname: mailer
    env_file:
      - .env
    networks:
      - backend
  permission:
    build: ./permission
    restart: always
    hostname: permission
    env_file:
      - .env
    networks:
      - backend
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
    links:
      - mailer
      - db
  db:
    image: mongo
    networks:
      - backend
    ports:
      - "22022:27017"
    volumes:
      - db:/data/db
    logging:
      driver: none
networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure
    external: true
volumes:
  db: