apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "10.240.0.11:6443"
    token: "abc123.def456ghi7sad211"
    unsafeSkipCAVerification: true
  tlsBootstrapToken: "abc123.def456ghi7sad211"
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    cloud-provider: gce
    feature-gates: ContainerCheckpoint=true
  taints: []
