secretGenerator:
- name: secret-env
  literals:
  - MONGO_URI=mongodb://db/db
  - MAILER_DSN=smtp.gmail.com
  - MAILER_FROM=safak0698@gmail.com
  - MAILER_PASSWORD=kqmb nrxj qshe wqsx
configMapGenerator:
- name: config-env
  literals:
  - API_GATEWAY_PORT=8000
  - TASK_SERVICE_PORT=8001
  - TASK_SERVICE_HOST=task
  - TOKEN_SERVICE_PORT=8002
  - TOKEN_SERVICE_HOST=token
  - USER_SERVICE_PORT=8003
  - USER_SERVICE_HOST=user
  - MAILER_SERVICE_PORT=8004
  - MAILER_SERVICE_HOST=mailer
  - PERMISSION_SERVICE_PORT=8005
  - PERMISSION_SERVICE_HOST=permission
  - MAILER_DISABLED=0
  - BASE_URI=http://35.242.207.9
resources:
  - db-deployment.yaml
  - gateway-deployment.yaml
  - user-deployment.yaml
  - token-deployment.yaml
  - mailer-deployment.yaml
  - permission-deployment.yaml
  - task-deployment.yaml
