apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  ports:
    - port: 8004
  selector:
    app: mailer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mailer
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - image: omersafakbebek/microservice-example-mailer
        name: mailer
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8004
          name: mailer
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 50m