apiVersion: v1
kind: Service
metadata:
  name: permission
  labels:
    app: permission
spec:
  ports:
    - port: 8005
  selector:
    app: permission
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: permission
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: permission
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  labels:
    app: permission
spec:
  replicas: 2
  selector:
    matchLabels:
      app: permission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: permission
    spec:
      containers:
      - image: omersafakbebek/microservice-example-permission
        name: permission
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8005
          name: permission
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 50m