apiVersion: v1
kind: Service
metadata:
  name: task
  labels:
    app: task
spec:
  ports:
    - port: 8001
  selector:
    app: task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  labels:
    app: task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - image: omersafakbebek/microservice-example-task
        name: task
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8001
          name: task