apiVersion: v1
kind: Service
metadata:
  name: task
  labels:
    app: task
spec:
  ports:
    - port: 8001
  selector:
    app: task
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  labels:
    app: task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - image: omersafakbebek/microservice-example-task
        name: task
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8001
          name: task
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 50m