apiVersion: v1
kind: Service
metadata:
  name: token
  labels:
    app: token
spec:
  ports:
    - port: 8002
  selector:
    app: token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  labels:
    app: token
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
      - image: omersafakbebek/microservice-example-token
        name: token
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8002
          name: token