apiVersion: v1
kind: Service
metadata:
  name: token
  labels:
    app: token
spec:
  ports:
    - port: 8002
  selector:
    app: token
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: token
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: token
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  labels:
    app: token
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
      - image: omersafakbebek/microservice-example-token
        name: token
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8002
          name: token
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 50m