apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - port: 8003
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: omersafakbebek/microservice-example-user
        name: user
        envFrom:
        - configMapRef:
            name: config-env
        - secretRef:
            name: secret-env
        ports:
        - containerPort: 8003
          name: user